import { useEffect, useMemo, useState } from 'react'
import type { ChangeEvent, FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { adminApi } from '../lib/api'
import { clearAuth, getStoredUser } from '../lib/auth'
import type { AdminBusinessDetail, AdminBusinessListItem, AdminOwnerOption } from '../types/api'

const emptyForm = { slug:'',name:'',description:'',category:'',logo_url:'',welcome_message:'',google_review_pc_url:'',google_review_mob_url:'',status:'ACTIVE',prefer_ai_comments:true,brand_primary_color:'#4f46e5',brand_secondary_color:'#312e81',nfc_enabled:true,qr_enabled:true,customer_settings:'{}',social_links:'[]',owner_user_id:'' }

export function AdminDashboardPage(){
  const navigate=useNavigate(); const user=getStoredUser()
  const [items,setItems]=useState<AdminBusinessListItem[]>([]); const [owners,setOwners]=useState<AdminOwnerOption[]>([])
  const [selected,setSelected]=useState<AdminBusinessDetail|null>(null); const [form,setForm]=useState(emptyForm); const [search,setSearch]=useState(''); const [status,setStatus]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('')
  const isAdmin=user?.role==='ADMIN'
  const assignedOwners=useMemo(()=>owners.filter(o=>o.business_id===null || o.business_id===selected?.id),[owners,selected])
  async function load(){ setLoading(true); setError(''); try { const [list,opts]=await Promise.all([adminApi.list({search:search||undefined,status:status||undefined}),adminApi.owners()]); setItems(list.items); setOwners(opts) } catch(e){setError(e instanceof Error?e.message:'Unable to load businesses.')} finally{setLoading(false)} }
  useEffect(()=>{ if(isAdmin) void load() },[isAdmin,search,status])
  if(!isAdmin){ return <main className="admin-page"><section className="admin-shell ra-card"><h1>Admin access required</h1><p>This area is available only to administrators.</p><button className="ra-button ra-button-secondary" onClick={()=>navigate('/account')}>Back to account</button></section></main> }
  const openNew=()=>{setSelected(null);setForm(emptyForm);setMessage('');setError('')}
  async function openBusiness(id:number){ try {setError('');const b=await adminApi.get(id);setSelected(b);setForm({slug:b.slug,name:b.name,description:b.description||'',category:b.category||'',logo_url:b.logo_url||'',welcome_message:b.welcome_message||'',google_review_pc_url:b.google_review_pc_url,google_review_mob_url:b.google_review_mob_url,status:b.status,prefer_ai_comments:b.prefer_ai_comments,brand_primary_color:b.brand_primary_color,brand_secondary_color:b.brand_secondary_color,nfc_enabled:b.nfc_enabled,qr_enabled:b.qr_enabled,customer_settings:JSON.stringify(b.customer_settings,null,2),social_links:JSON.stringify(b.social_links,null,2),owner_user_id:b.owner_user_id?String(b.owner_user_id):''});setMessage('')}catch(e){setError(e instanceof Error?e.message:'Unable to load business.')} }
  function field(k:keyof typeof form){return (e:ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm(v=>({...v,[k]:e.target.value}))}
  async function save(e:FormEvent){e.preventDefault();setSaving(true);setError('');setMessage('');let settings:Record<string,unknown>;let socialLinks:unknown[];try{settings=JSON.parse(form.customer_settings||'{}')}catch{setError('Customer settings must be valid JSON.');setSaving(false);return}try{socialLinks=JSON.parse(form.social_links||'[]');if(!Array.isArray(socialLinks))throw new Error()}catch{setError('Social links must be a JSON array.');setSaving(false);return} const body={slug:form.slug,name:form.name,description:form.description||null,category:form.category||null,logo_url:form.logo_url||null,welcome_message:form.welcome_message||null,google_review_pc_url:form.google_review_pc_url,google_review_mob_url:form.google_review_mob_url,status:form.status,prefer_ai_comments:form.prefer_ai_comments,brand_primary_color:form.brand_primary_color,brand_secondary_color:form.brand_secondary_color,nfc_enabled:form.nfc_enabled,qr_enabled:form.qr_enabled,customer_settings:settings,social_links:socialLinks,owner_user_id:form.owner_user_id?Number(form.owner_user_id):null};try{const b=selected?await adminApi.update(selected.id,body):await adminApi.create({...body,social_links:[]});setSelected(b);setMessage(selected?'Business updated successfully.':'Business created successfully.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save business.')}finally{setSaving(false)}}
  async function toggleStatus(b:AdminBusinessListItem){try{setError('');await adminApi.status(b.id,b.status==='ACTIVE'?'INACTIVE':'ACTIVE');setMessage(`${b.name} is now ${b.status==='ACTIVE'?'inactive':'active'}.`);await load();if(selected?.id===b.id) await openBusiness(b.id)}catch(e){setError(e instanceof Error?e.message:'Unable to change business status.')}}
  const logout=()=>{clearAuth();navigate('/login',{replace:true})}
  return <main className="admin-page"><div className="admin-shell">
    <header className="admin-header"><div><div className="ra-eyebrow">Platform administration</div><h1>Business management</h1><p>Manage every business, owner assignment, settings, branding and status from one place.</p></div><div className="owner-actions"><button className="ra-button ra-button-primary" onClick={openNew}>+ Add business</button><button className="ra-button ra-button-secondary" onClick={logout}>Sign out</button></div></header>
    {error&&<div className="owner-error">{error}</div>}{message&&<div className="admin-success">{message}</div>}
    <div className="admin-toolbar"><input className="ra-input" placeholder="Search business name, slug or category" value={search} onChange={e=>setSearch(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></div>
    <div className="admin-grid"><section className="admin-card"><div className="admin-card-head"><div><h2>All businesses</h2><p>{items.length} business{items.length===1?'':'es'}</p></div></div>{loading?<p className="muted">Loading…</p>:items.length===0?<p className="muted">No businesses found.</p>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Business</th><th>Owner</th><th>Status</th><th>Plan</th><th>Reviews</th><th>Rating</th><th>Actions</th></tr></thead><tbody>{items.map(b=><tr key={b.id}><td><strong>{b.name}</strong><small>{b.slug}{b.category?` · ${b.category}`:''}</small></td><td>{b.owner_name||'Unassigned'}<small>{b.owner_email||'—'}</small></td><td><span className={`status ${b.status==='INACTIVE'?'status-failed':''}`}>{b.status}</span></td><td>{b.plan}<small>{b.subscription_status}</small></td><td>{b.review_count}<small>{b.complaint_count} complaints</small></td><td>{b.average_rating??'—'}</td><td><div className="owner-actions"><button className="ra-button ra-button-secondary" onClick={()=>openBusiness(b.id)}>Edit</button><button className="ra-button ra-button-secondary" onClick={()=>toggleStatus(b)}>{b.status==='ACTIVE'?'Deactivate':'Activate'}</button></div></td></tr>)}</tbody></table></div>}</section>
      <section className="admin-card"><div className="admin-card-head"><div><h2>{selected?'Edit business':'Add new business'}</h2><p>{selected?`Business #${selected.id}`:'Create a business and optionally assign an existing owner.'}</p></div>{selected&&<button className="ra-button ra-button-secondary" onClick={openNew}>New</button>}</div>
      <form className="admin-form" onSubmit={save}><div className="settings-grid"><label>Business name<input className="ra-input" value={form.name} onChange={field('name')} required/></label><label>Slug<input className="ra-input" value={form.slug} onChange={field('slug')} required/></label><label>Category<input className="ra-input" value={form.category} onChange={field('category')}/></label><label>Status<select className="ra-input" value={form.status} onChange={field('status')}><option>ACTIVE</option><option>INACTIVE</option></select></label><label>Owner<select className="ra-input" value={form.owner_user_id} onChange={field('owner_user_id')}><option value="">Unassigned</option>{assignedOwners.map(o=><option key={o.id} value={o.id}>{o.full_name} — {o.email}</option>)}</select></label><label>Logo URL<input className="ra-input" value={form.logo_url} onChange={field('logo_url')}/></label><label>Google PC URL<input className="ra-input" value={form.google_review_pc_url} onChange={field('google_review_pc_url')} required/></label><label>Google mobile URL<input className="ra-input" value={form.google_review_mob_url} onChange={field('google_review_mob_url')} required/></label><label>Primary color<input className="ra-input" value={form.brand_primary_color} onChange={field('brand_primary_color')} required/></label><label>Secondary color<input className="ra-input" value={form.brand_secondary_color} onChange={field('brand_secondary_color')} required/></label></div>
      <label>Description<textarea className="ra-input" value={form.description} onChange={field('description')}/></label><label>Welcome message<textarea className="ra-input" value={form.welcome_message} onChange={field('welcome_message')}/></label><label>Customer settings JSON<textarea className="ra-input admin-json" value={form.customer_settings} onChange={field('customer_settings')}/></label><label>Social links JSON<textarea className="ra-input admin-json" value={form.social_links} onChange={field('social_links')}/></label>
      <div className="admin-checks"><label className="check-line"><input type="checkbox" checked={form.prefer_ai_comments} onChange={e=>setForm(v=>({...v,prefer_ai_comments:e.target.checked}))}/> Prefer AI comments</label><label className="check-line"><input type="checkbox" checked={form.nfc_enabled} onChange={e=>setForm(v=>({...v,nfc_enabled:e.target.checked}))}/> NFC enabled</label><label className="check-line"><input type="checkbox" checked={form.qr_enabled} onChange={e=>setForm(v=>({...v,qr_enabled:e.target.checked}))}/> QR enabled</label></div>
      <button className="ra-button ra-button-primary" disabled={saving}>{saving?'Saving…':selected?'Save business changes':'Create business'}</button></form></section>
    </div></div></main>
}
